flourishbhp/flourish-child

flourish_child/models/signals.py
When socio demographics in the same visit level change, update the academic performance in the same visit
=> Update academic Performance

flourish_child/models/academic_performance.py
Academic perfomace education_level is-equal to education_level in child socio demographic. Added to avoid data discrepancy and PEP8 Formatted
=> Added choices

flourish_child/forms/academic_performance_form.py
So it can use the provide the choices in the model + PEP8 Format update
=> Changed choices, should be disabled

flourish_child/models/signals.py
Initially academic performance was saving the readable part, instead of the actual db value. This update fixed that
=> Update signals.py for Academic Perfomance

flourish_child/models/signals.py
Maternal Delivery have no attribute instance
[BIRTH FORM.pdf](https://github.com/flourishbhp/flourish-child/files/8167491/BIRTH.FORM.pdf)
=> Random yellow page fix

flourish_child/forms/child_requisition_form.py
This reverts commit 237186200f242b3b26235602ea18126976551e8e.
=> Revert "Update child_requisition.py"

flourish_child/models/signals.py
- Added a pluggable  notification generator 
- PEP8 format
=> 5582 - Action Item & Pop-up for Newborn DOB and Name on Paper ICF

flourish_child/models/infant_feeding.py
=> 5932 - Infant feeding form

flourish_child/forms/child_assent_form.py
- validations were not being fired
- subject_identifier was returning null
=> child assent fix

flourish_child/admin/child_medical_history_admin.py
=> udpated child medical history admin

flourish_child/admin/child_immunization_history_admin.py, flourish_child/forms/__init__.py, flourish_child/forms/child_immunization_history_form.py
On quarterly calls, immunization hx crf does not pre-fill vaccines received at delivery visit. Please apply that the immunization hx crf should be pre-filled with vaccines received at delivery visit. CRF should be like the one for prior BHP participants with stem question. **Martha**
=> 5934 - Pre-fill vaccines received (at 2000D) to quarterly calls Immunisation hx crf.

flourish_child/admin/child_preg_testing_admin.py, flourish_child/models/child_preg_testing.py
Added last menstrual period questions
=> updated child pregnancy model and admin

flourish_child/models/signals.py
- The new born babe was going on visit 2000 instead of visit 2000D
- A flag was placed so it won't be the issue
=> #7189 - Schedule Fix

flourish_child/choices.py, flourish_child/models/child_penn_cnb.py
=> Added extra response to Q1 on the Penn cnb model

flourish_child/list_data.py
String identifiers and labels in the 'flourish_child.list_data.py' file were shortened to enhance code readability. This refactoring also affects related validation function in 'infant_arv_prophylaxis_post_follow_form_validator.py', where a response value is updated accordingly. The changes do not affect the original functionality of the code.
=> :recycle: refactor(List-Data): Update identifiers and labels in list_data file

flourish_child/helper_classes/brain_ultrasound_helper.py
Improved error handling in is_enrolled_brain_ultrasound method in the brain_ultrasound_helper class. Separate exception cases have been specified to handle RequestExceptions and decoding errors in JSON response. Also, added JSON import for error handling.
=> fix(Helper-classes): Refactor error handling in brain_ultrasound_helper.py

flourish_child/models/infant_arv_exposure.py
Removed nullable attributes that were not needed in the "Infant ARV Exposure" model in the flourish_child app. The model class meta description has also been improved to better reflect its context, specifically adjusted to "Infant ARV Exposure at Delivery". This also necessitated changes in the corresponding validation rules in the flourish_child_validations app to remove superfluous validations.
=> Update and optimize Infant ARV Exposure model

flourish_child/models/child_safi_stigma.py
=> 7316 - Feedback (Caregiver and Child Stigma CRFs for version 4.0 reconsenting)

flourish_child/forms/child_visit_form.py
Action Item does not exist, seems like it was deleted and not removed from the child visit_form
=> Yellow page fix (Testing)

flourish_child/admin/academic_performance_admin.py, flourish_child/admin/child_food_security_questionnaire_admin.py
Revised instructions for Clinic Staff in the Child Food Security Questionnaire Admin and Academic Performance Admin forms. The new instructions are more detailed and provide clearer guidelines for data collection. Also, the field structure in the Interview Focus Group Interest form has been streamlined for enhanced clarity and ease of use.
=> refactor(Admin-forms): Update food security and academic performance forms

flourish_child/admin/academic_performance_admin.py, flourish_child/admin/child_food_security_questionnaire_admin.py, flourish_child/templates/edc_model_admin/edc_additional_instructions.html, flourish_child/templates/edc_model_admin/edc_instructions.html
This update refactors the way special instructions are handled in admin views. The instructions field has been moved from the 'add_view' method to the main class body in two different admin.py files. Also, these changes introduced a new template for handling additional instructions. Signed-off-by: nmunatsibw
=> (Refactor): Update instructions in admin views

flourish_child/choices.py, flourish_child/forms/child_tb_referral_outcome_form.py, flourish_child/list_data.py, flourish_child/models/child_tb_referral.py, flourish_child/models/child_tb_referral_outcome.py, flourish_child/models/child_tb_screening.py
=> #7484 tony

flourish_child/admin/child_tb_referral_outcome_admin.py, flourish_child/choices.py, flourish_child/models/child_tb_screening.py, flourish_child/settings.py
This update introduces some changes in the 'flourish_child' Django application. The models, settings and choices used within this application have been refined. The 'choices.py' file has been modified adjusting some tuple values. The 'settings.py' file now includes the path to the templates directory. An important enhancement was added to the 'child_tb_screening.py' model to compute TB diagnosis based on a child's age at the time they were screened. A horizontal filter for 'tests_performed' was also added to the child_tb_referral_outcome_admin dashboard. Signed-off-by: nmunatsibw
=> (refactor): Update model, settings and choices in 'flourish_child' application

flourish_child/admin/child_tb_screening_admin.py, flourish_child/forms/child_tb_screening_form.py, flourish_child/models/child_tb_screening.py
Added new fields to the Child TB Screening Form model and updated the admin interface of the Flourish-Child app accordingly. This includes choice fields for previous screening results and additional checks for form data validation. Improved the user interface for TB screening by introducing conditional field sets and an option for specifying 'other' diagnoses.
=> (Feature): Add additional fields to Child TB Screening

flourish_child/admin/exportaction_mixin.py
The code in ExportActionMixin has been significantly refactored. Reorganized import statements are only a part of the changes. New helper methods have been added to reduce complexity and improve code readability. For example, `get_caregiver_sid` and `caregiver_subject_consents` methods have been added. Variable instantiation and various methods have been updated for better clarity as well.
=> (refactor): Clean up and improve readability of ExportActionMixin
